# Generated by Django 5.1.1 on 2024-12-02 13:47


from django.conf import settings
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations import state
from django.db.models import (
    BigAutoField,
    CharField,
    CheckConstraint,
    DateTimeField,
    ForeignKey,
    GeneratedField,
    ManyToManyField,
    PositiveSmallIntegerField,
    Q,
    TextField,
    UniqueConstraint,
    Value,
)
from django.db.models.deletion import PROTECT
from django.db.models.functions import Cast, Concat, Length, Left, LPad, Replace, Right, Substr
from django.db.models.lookups import GreaterThanOrEqual, LessThanOrEqual
from modelcluster.fields import ParentalKey

from wellplated.models import PREFIX_ID_LENGTH

PREFIX_ID_LENGTH = 12
CONTAINER_CODE_LENGTH = 1 + 2 + PREFIX_ID_LENGTH  # bottom row, right column


format_checks = {
    'format-bottom-row-length-1': Q(bottom_row__length=1),
    'format-bottom-row-gte-A': Q(bottom_row__gte='A'),
    'format-bottom-row-lte-P': Q(bottom_row__lte='P'),
    'format-right-column-gte-1': Q(right_column__gte=1),
    'format-right-column-lte-24': Q(right_column__lte=24),
    # Dot/period separates Container serial code from Well label
    'format-prefix-no-dot': ~Q(prefix__contains='.'),
    'format-prefix-length-lte-11': Q(prefix__length__lte=PREFIX_ID_LENGTH - 1),
}

well_checks = {
    'well-bottom-row-gte-A': GreaterThanOrEqual(Left('label', 1), 'A'),
    'well-bottom-row-lte-format-max': LessThanOrEqual(Left('label', 1), Left('container', 1)),
    'well-right-column-gte-1': GreaterThanOrEqual(
        Cast(Right('label', 2), PositiveSmallIntegerField()),
        1
    ),
    'well-right-column-lte-format-max': LessThanOrEqual(
        Right('label', 2),
        Cast(Substr('container', 2, 4), PositiveSmallIntegerField())
    ),
    'well-container-code-label-length-19': Q(
        # container code, dot, label row, label column
        container_code_label__length=CONTAINER_CODE_LENGTH + 1 + 1 + 2
    ),
    'well-container-code-label-has-1-dot': Q(
        container_code_label__length=(
            Length(Replace('container_code_label', Value('.'), Value(''))) + 1
        )
    ),
}


def constrain_models() -> list[migrations.AddConstraint]:
    """Forbid out-of-bounds at the database level"""
    return [
        migrations.AddConstraint(
            constraint=CheckConstraint(condition=condition, name=name),
            model_name='format',
        ) for name, condition in format_checks.items()
    ] + [
        migrations.AddConstraint(
            constraint=CheckConstraint(condition=condition, name=name),
            model_name='well',
        ) for name, condition in well_checks.items()
    ]


def create_untracked(apps: state.StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Infinite source and sink

    Leave unused low numbers between start and end for future special purpose use.
    """
    for pk, purpose in {0: 'start', 999: 'end'}.items():
        container = apps.get_model('wellplated', 'Container').objects.create(
            id=pk,
            code=purpose,
            format=apps.get_model('wellplated', 'Format').objects.create(
                bottom_row='A', right_column=1, prefix=purpose, purpose=purpose
            ),
        )
        container.wells.add(apps.get_model('wellplated', 'Well')(label='A01'))
        container.wells.commit()


class Migration(migrations.Migration):
    initial = True

    dependencies = (migrations.swappable_dependency(settings.AUTH_USER_MODEL),)

    operations = (
        migrations.CreateModel(
            name='Format',
            fields=[
                (
                    'id',
                    BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('bottom_row', CharField(default='H', editable=False, max_length=1)),
                (
                    'right_column',
                    PositiveSmallIntegerField(default=12, editable=False, max_length=2),
                ),
                ('prefix', CharField(editable=False, max_length=PREFIX_ID_LENGTH - 1)),
                (
                    'bottom_right_prefix',
                    GeneratedField(
                        db_persist=True,
                        expression=Concat(
                            'bottom_row',
                            LPad(Cast('right_column', CharField()), 2, Value('0')),
                            'prefix',
                        ),
                        # bottom row, right column
                        output_field=CharField(max_length=1 + 2 + PREFIX_ID_LENGTH - 1),
                        unique=True,
                    ),
                ),
                ('created_at', DateTimeField(auto_now_add=True, editable=False)),
                ('purpose', TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                (
                    'id',
                    BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'code',
                    GeneratedField(
                        db_persist=True,
                        expression=Concat(
                            'format',
                            LPad(Cast('id', CharField()), Value(CONTAINER_CODE_LENGTH) - Length('format'), Value('0')),
                        ),
                        editable=False,
                        output_field=CharField(max_length=CONTAINER_CODE_LENGTH),
                        unique=True,
                    ),
                ),
                ('created_at', DateTimeField(auto_now_add=True, editable=False)),
                (
                    'format',
                    ForeignKey(
                        editable=False,
                        on_delete=PROTECT,
                        related_name='containers',
                        to='wellplated.format',
                        to_field='bottom_right_prefix',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                (
                    'id',
                    BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'container',
                    ParentalKey(
                        db_column='container_code',
                        editable=False,
                        on_delete=PROTECT,
                        related_name='wells',
                        to='wellplated.container',
                        to_field='code',
                    ),
                ),
                ('label', CharField(editable=False, max_length=3)),
                (
                    'container_code_label',
                    GeneratedField(
                        db_persist=True,
                        editable=False,
                        expression=Concat('container', Value('.'), 'label'),
                        # dot, row, column
                        output_field=CharField(max_length=CONTAINER_CODE_LENGTH + 1 + 1 + 2),
                        unique=True,
                    ),
                ),
            ],
        ),
        *constrain_models(),
        migrations.RunPython(create_untracked, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'id',
                    BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    ForeignKey(
                        on_delete=PROTECT, related_name='plans_created', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                (
                    'id',
                    BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'plan',
                    ForeignKey(on_delete=PROTECT, related_name='transfers', to='wellplated.plan'),
                ),
                ('source', ForeignKey(on_delete=PROTECT, related_name='+', to='wellplated.well')),
                ('sink', ForeignKey(on_delete=PROTECT, related_name='+', to='wellplated.well')),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='sinks',
            field=ManyToManyField(
                related_name='sources', through='wellplated.Transfer', to='wellplated.well'
            ),
        ),
    )
