default_language_version:
    python: python3.12 # Using .python-version would be nice
repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2025.06.04
      hooks:
          - id: actionlint
          - id: codespell
          - id: cookiecutter
          - id: dot-yaml
          - id: includes-sh
          - id: mypy
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: uv-pip-compile
          - id: yamllint
