default_language_version:
    python: python3.12 # Using .python-version would be nice
repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2024.38.1
      hooks:
          - id: dot-yaml
          - id: includes-sh
          - id: mypy
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: uv-pip-compile
          - id: yamllint
    # TODO auto-detect languages in Helicopyter
    - repo: local
      hooks:
          - id: gitignore
            entry: >
                bash -c '
                curl -s https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore >
                .gitignore'
            language: system
            name: gitignore
            pass_filenames: false
