default_language_version:
    python: python3.12 # Using .python-version would be nice
repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2025.08.01
      hooks:
          # Auto-fix and -generate first, so reported line numbers match working tree
          - id: actionlint
          - id: codespell
          - id: cookiecutter
          - id: includes-sh
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: uv-pip-compile
          # Lint-only second, so reported line numbers match working tree
          - id: dot-yaml
          - id: yamllint
          # mypy last because it's so slow
          - id: mypy
    - repo: local
      hooks:
          - id: schema
            name: schema
            entry: bash -c 'python -m manage migrate && python -m manage schema'
            language: system
