name: Check
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version-file: .nvmrc
            - run: npm install --frozen-lockfile

            - uses: astral-sh/setup-uv@v5
            - run: uv venv && . includes.sh ups

            - run: source includes.sh && a && pcam --color always --show-diff-on-failure
            - run: .venv/bin/python -m manage check
            - run: |
                  .venv/bin/python -m pytest --cov=wellplated --cov-report=term-missing:skip-covered
            - run: .venv/bin/python -m build
            - run: .venv/bin/twine check dist/*

    summarize:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash includes.sh summarize

on: # yamllint disable-line rule:truthy
    - pull_request