name: Check
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: source .biobuddies/includes.bash forceready
            - run: |
                  source .biobuddies/includes.bash && a && pcam --color always --show-diff-on-failure
            - run: .venv/bin/python -m manage check
            - run: |
                  .venv/bin/python -m pytest --cov=wellplated --cov-report=term-missing:skip-covered
            - run: .venv/bin/python -m build
            - run: .venv/bin/twine check dist/*

    summarize:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash summarize

on: # yamllint disable-line rule:truthy
    - pull_request
